services:
  nginx:
    image: 'nginx:1.23.3-alpine'
    volumes:
      - './index.html:/var/www/waybackinator.com/index.html:ro'
      - './favicon.ico:/var/www/waybackinator.com/favicon.ico:ro'
      - './nginx.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '8000:80'

  waybackinator:
    image: 'node:19.4.0-alpine3.16'
    volumes:
      - './waybackinator.js:/usr/local/bin/waybackinator.js:ro'
      - './tlds-alpha-by-domain.txt:/etc/waybackinator/tlds-alpha-by-domain.txt:ro'
    command: 'node /usr/local/bin/waybackinator.js /etc/waybackinator/tlds-alpha-by-domain.txt'
